classBasedViews/advbbc/advbbc/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from basic_app import views
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.IndexView.as_view()),
    url(r'^basic_app/', include('basic_app.urls'))
]

classBasedViews/advbbc/basic_app/urls.py
from django.conf.urls import url
from basic_app import views

app_name = 'basic_app'

urlpatterns = [
    url(r'^$', views.SchoolListView.as_view(), name='list'),
    url(r'^(?P<pk>\d+)/$', views.SchoolDetailView.as_view(), name='detail'),
    url(r'^create/', views.SchoolCreateView.as_view(), name='create'),
    url(r'^update/(?P<pk>\d+)/$', views.SchoolUpdateView.as_view(), name='update'),
    url(r'^delete/(?P<pk>\d+)/$', views.SchoolDeleteView.as_view(), name='delete'),    
]

classBasedViews/advbbc/basic_app/models.py
from django.db import models
from django.core.urlresolvers import reverse
# Create your models here.
class School(models.Model):
    name = models.CharField(max_length=265)
    principal = models.CharField(max_length=256)
    location = models.CharField(max_length=256)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("basic_app:detail", kwargs={'pk':self.pk})

class Student(models.Model):
    name = models.CharField(max_length=256)
    age = models.PositiveIntegerField()
    school = models.ForeignKey(School, related_name='students')


    def __str__(self):
        return self.name

classBasedViews/advbbc/basic_app/views.py
from django.shortcuts import render
from django.views.generic import (View, TemplateView, ListView, DetailView,
                                    CreateView, UpdateView, DeleteView)
from django.core.urlresolvers import reverse_lazy

from basic_app.models import School, Student
# Create your views here.

class IndexView(TemplateView):
    template_name = 'index.html'


class SchoolListView(ListView):
    model = School
    context_object_name = 'schools'

class SchoolDetailView(DetailView):
    model = School
    template_name = 'basic_app/school_detail.html'
    context_object_name = 'school_detail'

class SchoolCreateView(CreateView):
    model = School
    fields = ('name', 'principal', 'location')

class SchoolUpdateView(UpdateView):
    model = School
    fields = ('name', 'principal')

class SchoolDeleteView(DeleteView):
    model = School
    success_url = reverse_lazy("basic_app:list")

classBasedViews/advbbc/basic_app/templates/basic_app/basic_app_base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
    integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

  </head>
  <body>

    <nav class="navbar navba-default navbar-static-top">
      <ul class='nav navbar-nav'>


        <li> <a class='navbar-brand' href="{% url  'basic_app:list'%}">Schools</a> </li>
        <li> <a class='navbar-link' href="{% url 'admin:index' %}">Admin</a> </li>
        <li> <a class='navbar-link' href="#"></a> </li>
      </ul>
    </nav>

    <div class="container">
      {% block body_block %}
      {% endblock %}
    </div>

  </body>
</html>

classBasedViews/advbbc/basic_app/templates/basic_app/school_confirm_delete.html
{% extends "basic_app/basic_app_base.html" %}

{% block body_block %}
  <h1>Delete {{school.name}}?</h1>
  <form method="post">
    {% csrf_token %}
    <input type="submit"  class='btn btn-danger' value="Delete">

    <a href="{% url 'basic_app:detail' pk=school.pk %}">Cancel</a>
  </form>


{% endblock %}

classBasedViews/advbbc/basic_app/templates/basic_app/school_detail.html
{% extends "basic_app/basic_app_base.html" %}

{% block body_block %}
<div class="jumbotron">
  <h1>Welcome to school detail page</h1>
  <h2>School Details: </h2>
  <p>{{school_detail.name}}</p>
  <p>{{school_detail.principal}}</p>
  <p>{{school_detail.location}}</p>

  <h3>Students:</h3>
  {% for student in school_detail.students.all %}
    <p>{{student.name}} who is {{student.age}} old.</p>
  {% endfor %}
</div>

<div class="container">
  <p><a class='btn btn-warning' href="{% url 'basic_app:update' pk=school_detail.pk %}">Update</a></p>
</div>
{% endblock %}

classBasedViews/advbbc/basic_app/templates/basic_app/school_form.html
{% extends "basic_app/basic_app_base.html" %}

{% block body_block %}

  <h1>
    {% if not form.instance.pk %}
    Create School
    {% else %}
    Update School
    {% endif %}
  </h1>

  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class='btn btn-primary' value="Submit">
  </form>

{% endblock %}

classBasedViews/advbbc/basic_app/templates/basic_app/school_list.html
{% extends "basic_app/basic_app_base.html" %}

{% block body_block %}
  <h1>Welcome to list of schools</h1>

  <ol>
    {% for school in schools %}
      <h2>
        <li>
          <a href="{{school.id}}">{{school.name}}</a>
        </li>
      </h2>
    {% endfor %}
  </ol>
{% endblock %}

classBasedViews/advbbc/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
    integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

  </head>
  <body>

    <nav class="navbar navba-default navbar-static-top">
      <ul class='nav navbar-nav'>


        <li> <a class='navbar-brand' href="{% url  'basic_app:list'%}">Schools</a> </li>
        <li> <a class='navbar-link' href="{% url 'admin:index' %}">Admin</a> </li>
        <li> <a class='navbar-link' href="#"></a> </li>
      </ul>
    </nav>

    <div class="container">
      {% block body_block %}
      {% endblock %}
    </div>

  </body>
</html>

classBasedViews/advbbc/templates/index.html
{% extends "base.html" %}

{% block body_block %}
  <div class="jumbotron">
    <h1>Welcome</h1>
  </div>
{% endblock %}